import Sidebar from "@/ui/sidebar/Sidebar";
import styles from "@/ui/dashboard/dashboard.module.css";

export const metadata = {
  title: "NextJS Dashboard",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return (
    <div className={styles.container}>
      <div className={styles.menu}>
        <Sidebar />
      </div>
    </div>
  );
};

export default layout;
